In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

In [6]:
list = [1,2,3,4,5,6]
print(list)

[1, 2, 3, 4, 5, 6]


In [9]:
print("1D Array")
list = [1,2,3,4,5,6]
print(list)

1D Array
[1, 2, 3, 4, 5, 6]


In [11]:
a=np.array([5,4,3,2,1])
print(a)

[5 4 3 2 1]


In [13]:
print("2D Array")
b=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(b)

2D Array
[[1 2 3 4 5]
 [5 4 3 2 1]]
