In [1]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [ ]:
#The Basic Numpy

In [56]:
list = [1,2,3,4,5,6]
print(list)

[1, 2, 3, 4, 5, 6]


In [54]:
a=np.array([1,2,3,4,5] , dtype='int16')
b=np.array([[1,2,3,4,5],[6,7,8,9,10]] , dtype='int32')
print(a)
print(b)

[1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [55]:
print(a.ndim)
print(b.ndim)
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)

1
2
(5,)
(2, 5)
int16
int32


In [13]:
print("1D Array")
list = [1,2,3,4,5,6]
print(list)

1D Array
[1, 2, 3, 4, 5, 6]


In [14]:
a=np.array([5,4,3,2,1])
print(a)

[5 4 3 2 1]


In [15]:
print("2D Array")
b=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(b)

2D Array
[[1 2 3 4 5]
 [5 4 3 2 1]]


In [ ]:
#Accessing and changing specific elements , row and columns

In [90]:
#Geting specific Element
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
# print(a)
print(a[0,2])

3


In [96]:
#Geting specific Row
print(a[0:1])
print(a[1:])
print(a[1,:])

[[1 2 3 4 5 6]]
[[ 7  8  9 10 11 12]]
[ 7  8  9 10 11 12]


In [95]:
#Geting specific Columns
print(a[:,2])
print(a[:,3])

[3 9]
[ 4 10]


In [103]:
#Geting specific littile more fancy
print(a[1, 1:6:3])
print(a[0, 1:6:3])

[ 8 11]
[2 5]


In [104]:
#Initializing Differnt type of Array

In [113]:
print("1 x 2")
np.zeros((1,2))

1 x 2


In [16]:
b.transpose()

array([[1, 5],
       [2, 4],
       [3, 3],
       [4, 2],
       [5, 1]])

In [17]:
print("3D Array")
b=np.array([[1,2,3,4,5],[5,4,3,2,1],[5,4,3,2,1]])
print(b)

3D Array
[[1 2 3 4 5]
 [5 4 3 2 1]
 [5 4 3 2 1]]


In [23]:
np.empty((4,4),dtype = int)

array([[23925768161198147, 32370111954616435, 28147918584217692,
        32369819897299061],
       [28147914290036833, 31525648366174300, 31244169099083897,
        32088628387381358],
       [30399748463001711, 28429402150731877, 30399800002281574,
        29555319237247092],
       [32088624093986931, 31807166292557945, 28429470870863980,
        30399714104377389]])

In [24]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.ones((3,4) ,dtype = float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros((3,4),dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
a=np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
a=np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


In [34]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [35]:
a=a.reshape((3,3))
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [36]:
b=a.flatten()
print(b)

[ 2  4  6  8 10 12 14 16 18]


In [37]:
c=a.ravel()
print(c)

[ 2  4  6  8 10 12 14 16 18]
