In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5,6]
print(list)

[1, 2, 3, 4, 5, 6]


In [3]:
print("1D Array")
list = [1,2,3,4,5,6]
print(list)

1D Array
[1, 2, 3, 4, 5, 6]


In [4]:
a=np.array([5,4,3,2,1])
print(a)

[5 4 3 2 1]


In [5]:
print("2D Array")
b=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(b)

2D Array
[[1 2 3 4 5]
 [5 4 3 2 1]]


In [7]:
b.transpose()

array([[1, 5, 5],
       [2, 4, 4],
       [3, 3, 3],
       [4, 2, 2],
       [5, 1, 1]])

In [6]:
print("3D Array")
b=np.array([[1,2,3,4,5],[5,4,3,2,1],[5,4,3,2,1]])
print(b)

3D Array
[[1 2 3 4 5]
 [5 4 3 2 1]
 [5 4 3 2 1]]


In [8]:
np.empty((4,4),dtype= int)

array([[7598805615504746854, 8249803397792427631,      11484742549515,
        6052837899394762240],
       [8102949291483071017, 8386107220301213285, 7598817722882812003,
        7598543875601298032],
       [8389765631558969198, 8313474914660283487, 8386107536418431348,
        7211242064543114612],
       [7809093802562773605, 3346848972108887393, 8389765631525419376,
        7304668598129292383]])

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((3,4) ,dtype = float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3,4),dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])